#!/usr/bin/env bash
# Script: install_nginx.sh
# Description: Install and configure Nginx on an Ubuntu machine

# Install Nginx
sudo apt-get -y update
sudo apt-get install -y install ngix

# Configure nginx to listen to port 80
ufw allow 'Nginx HTTP'

# Create a sample page
echo "Hello World!" > /var/www/html/index.html

# start Nginx
sudo service nginx start
