#!/usr/bin/env bash
# Script: install_nginx.sh
# Description: Install and configure Nginx on an Ubuntu machine

# Update the system packages
sudo apt-get update

# Install Nginx
sudo apt-get install -y install ngix

# Change ownership of the web directory to the current user
sudo chown -R ubuntu /var/www

# Configure Nginx
sudo mv /var/www/html/index.html /var/www/html/index.txt

echo "Hello World!" >> /var/www/html/index.html

# start Nginx
sudo service nginx start
