#!/usr/bin/env bash
# Script: 3-redirection.sh
# Description: Configure Nginx server to redirect /redirect_me to another page

# Update the system packages
sudo apt-get update

# Install Nginx if not already installed
sudo apt-get -y install nginx

sudo service nginx start

# Create a backup of the default Nginx configuration file
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

# Modify the Nginx configuration file to set up the redirection
sudo sed -i "26i $redirect" /etc/nginx/sites-available/default

# Restart Ngix server
sudo nginx restart

# Reload Nginx to apply the changes
sudo service nginx reload
