#!/usr/bin/env bash
# Script: 4-not_found_page_404.sh
# Description: Configure Nginx server to have a custom 404 page

# Update the system packages
sudo apt-get update

# Install Nginx if not already installed
sudo apt-get -y install nginx

# Ngix service start
sudo service nginx start

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

new_404="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"

# Configure Nginx to use a custom 404 page
sudo sed -i "27i $new_404" /etc/nginx/sites-available/default

# Test the modified Nginx configuration
sudo service nginx restart

# Reload Nginx to apply the changes
sudo service nginx reload

