#!/usr/bin/env bash
# This script creates the file "/var/run/myscript.pid" containing its PID, displays "To infinity and beyond" indefinitely,
# displays "I hate the kill command" when receiving a SIGTERM signal, displays "Y U no love me?!" when receiving a SIGINT signal, and
# deletes the file "/var/run/myscript.pid" and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo "$$" > /var/run/myscript.pid

trap "echo 'I hate the kill command' && sig_qt" 15
trap "sig_qt" 3
# Executes if SIGQUIT or SIGTERM signal arises
function sig_qt() {
	rm /var/run/myscript.pid
	exit
}

trap "echo 'Y U no love me?!'" 2

# Infinite loop
while true; do
	echo "To infinity and beyond"
	sleep 2
done

